/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_core_internal_net_proxy_unix_UnixProxyProvider */

#ifndef _Included_org_eclipse_core_internal_net_proxy_unix_UnixProxyProvider
#define _Included_org_eclipse_core_internal_net_proxy_unix_UnixProxyProvider
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: isGnomeLibLoaded */
/*
 * Class:     org_eclipse_core_internal_net_proxy_unix_UnixProxyProvider
 * Method:    gconfInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_core_internal_net_proxy_unix_UnixProxyProvider_gconfInit
  (JNIEnv *, jclass);

/*
 * Class:     org_eclipse_core_internal_net_proxy_unix_UnixProxyProvider
 * Method:    getGConfProxyInfo
 * Signature: (Ljava/lang/String;)Lorg/eclipse/core/internal/net/ProxyData;
 */
JNIEXPORT jobject JNICALL Java_org_eclipse_core_internal_net_proxy_unix_UnixProxyProvider_getGConfProxyInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_eclipse_core_internal_net_proxy_unix_UnixProxyProvider
 * Method:    getGConfNonProxyHosts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_eclipse_core_internal_net_proxy_unix_UnixProxyProvider_getGConfNonProxyHosts
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
