source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               iconpacks/,\
               css/default.css,\
               Application.e4xmi,\
               OSGI-INF/org.eclipse.ui.examples.urlmodifier.IconPackModifier.xml
