/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp */

#ifndef _Included_org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp
#define _Included_org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp
 * Method:    open
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp_open
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jint);

/*
 * Class:     org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp
 * Method:    closeHandle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp_closeHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp
 * Method:    getIEProxyConfigForCurrentUser
 * Signature: (Lorg/eclipse/core/internal/net/proxy/win32/winhttp/WinHttpCurrentUserIEProxyConfig;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp_getIEProxyConfigForCurrentUser
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp
 * Method:    getProxyForUrl
 * Signature: (ILjava/lang/String;Lorg/eclipse/core/internal/net/proxy/win32/winhttp/WinHttpAutoProxyOptions;Lorg/eclipse/core/internal/net/proxy/win32/winhttp/WinHttpProxyInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp_getProxyForUrl
  (JNIEnv *, jclass, jint, jstring, jobject, jobject);

/*
 * Class:     org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp
 * Method:    detectAutoProxyConfigUrl
 * Signature: (Lorg/eclipse/core/internal/net/proxy/win32/winhttp/AutoProxyHolder;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp_detectAutoProxyConfigUrl
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp
 * Method:    getLastErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eclipse_core_internal_net_proxy_win32_winhttp_WinHttp_getLastErrorMessage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
