<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="application"
    nsURI="http://www.eclipse.org/ui/2008/Application" nsPrefix="application">
  <eClassifiers xsi:type="ecore:EClass" name="MApplicationElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MApplication" eSuperTypes="#//MApplicationElement">
    <eTypeParameters name="W">
      <eBounds eClassifier="#//MWindow">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="windows" lowerBound="1"
        upperBound="-1" containment="true">
      <eGenericType eTypeParameter="#//MApplication/W"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        upperBound="-1" eType="#//MCommand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="#//IEclipseContext"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MPart" eSuperTypes="#//MApplicationElement">
    <eTypeParameters name="P">
      <eBounds eClassifier="#//MPart">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="menu" eType="#//MMenu"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolBar" eType="#//MToolBar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="policy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The policy would define how the parent displays the children (stack/sashforms)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        containment="true" eOpposite="#//MPart/parent">
      <eGenericType eTypeParameter="#//MPart/P"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeChild">
      <eGenericType eTypeParameter="#//MPart/P"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="handlers" upperBound="-1"
        eType="#//MHandler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eOpposite="#//MPart/children">
      <eGenericType eClassifier="#//MPart">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="#//IEclipseContext"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MStack">
    <eGenericSuperTypes eClassifier="#//MPart">
      <eTypeArguments eClassifier="#//MItemPart">
        <eTypeArguments/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSashForm">
    <eTypeParameters name="P">
      <eBounds eClassifier="#//MPart">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weights" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="#//MPart">
      <eTypeArguments eTypeParameter="#//MSashForm/P"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MContributedPart">
    <eTypeParameters name="P">
      <eBounds eClassifier="#//MPart">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//MItemPart">
      <eTypeArguments eTypeParameter="#//MContributedPart/P"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MContribution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MContribution" abstract="true" eSuperTypes="#//MApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistedState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MHandler" eSuperTypes="#//MContribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//MCommand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MItem" abstract="true" eSuperTypes="#//MApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MHandledItem" eSuperTypes="#//MItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="#//MCommand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="menu" eType="#//MMenu"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wbCommand" eType="#//ParameterizedCommand"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//MParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMenuItem" eSuperTypes="#//MHandledItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="separator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MToolBarItem" eSuperTypes="#//MHandledItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MItemContainer" abstract="true" eSuperTypes="#//MApplicationElement">
    <eTypeParameters name="I">
      <eBounds eClassifier="#//MItem"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//MItemContainer/I"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMenu">
    <eGenericSuperTypes eClassifier="#//MItemContainer">
      <eTypeArguments eClassifier="#//MMenuItem"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MToolBar">
    <eGenericSuperTypes eClassifier="#//MItemContainer">
      <eTypeArguments eClassifier="#//MToolBarItem"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTrimmedPart">
    <eTypeParameters name="P">
      <eBounds eClassifier="#//MPart">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topTrim" eType="#//MToolBarContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftTrim" eType="#//MToolBarContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightTrim" eType="#//MToolBarContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bottomTrim" eType="#//MToolBarContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientArea" containment="true">
      <eGenericType eClassifier="#//MPart">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//MPart">
      <eTypeArguments eTypeParameter="#//MTrimmedPart/P"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MItemPart">
    <eTypeParameters name="P">
      <eBounds eClassifier="#//MPart">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//MPart">
      <eTypeArguments eTypeParameter="#//MItemPart/P"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//MItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MWindow">
    <eTypeParameters name="P">
      <eBounds eClassifier="#//MPart">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="#//MItemPart">
      <eTypeArguments eTypeParameter="#//MWindow/P"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MCommand" eSuperTypes="#//MApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IEclipseContext" instanceClassName="org.eclipse.e4.core.services.context.IEclipseContext"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="MToolBarContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolbars" upperBound="-1"
        eType="#//MToolBar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ParameterizedCommand" instanceClassName="org.eclipse.core.commands.ParameterizedCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="MParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
