<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="application" nsURI="http://www.eclipse.org/ui/2010/UIModel/application"
    nsPrefix="application">
  <eClassifiers xsi:type="ecore:EDataType" name="IEclipseContext" instanceClassName="org.eclipse.e4.core.contexts.IEclipseContext"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringToStringMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//commands/Command" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addons" upperBound="-1"
        eType="#//Addon" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//commands/Category" containment="true"/>
    <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
      <eTypeArguments eClassifier="#//ui/basic/Window"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//ui/Context"/>
    <eGenericSuperTypes eClassifier="#//commands/HandlerContainer"/>
    <eGenericSuperTypes eClassifier="#//commands/BindingTableContainer"/>
    <eGenericSuperTypes eClassifier="#//descriptor/basic/PartDescriptorContainer"/>
    <eGenericSuperTypes eClassifier="#//commands/Bindings"/>
    <eGenericSuperTypes eClassifier="#//ui/menu/MenuContributions"/>
    <eGenericSuperTypes eClassifier="#//ui/menu/ToolBarContributions"/>
    <eGenericSuperTypes eClassifier="#//ui/menu/TrimContributions"/>
    <eGenericSuperTypes eClassifier="#//ui/SnippetContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistedState" upperBound="-1"
        eType="#//StringToStringMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributorURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transientData" upperBound="-1"
        eType="#//StringToObjectMap" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contribution" abstract="true" eSuperTypes="#//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Addon" eSuperTypes="#//Contribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringToObjectMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eSubpackages name="commands" nsURI="http://www.eclipse.org/ui/2010/UIModel/application/commands"
      nsPrefix="commands">
    <eClassifiers xsi:type="ecore:EClass" name="BindingTableContainer" abstract="true"
        interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingTables" upperBound="-1"
          eType="#//commands/BindingTable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootContext" upperBound="-1"
          eType="#//commands/BindingContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bindings" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingContexts" upperBound="-1"
          eType="#//commands/BindingContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingContext" eSuperTypes="#//ApplicationElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//commands/BindingContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingTable" eSuperTypes="#//ApplicationElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
          eType="#//commands/KeyBinding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingContext" lowerBound="1"
          eType="#//commands/BindingContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Command" eSuperTypes="#//ApplicationElement">
      <eOperations name="getLocalizedCommandName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getLocalizedDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//commands/CommandParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="category" eType="#//commands/Category"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CommandParameter" eSuperTypes="#//ApplicationElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Handler" eSuperTypes="#//Contribution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
          eType="#//commands/Command"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HandlerContainer" abstract="true"
        interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="handlers" upperBound="-1"
          eType="#//commands/Handler" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KeyBinding" eSuperTypes="#//ApplicationElement #//commands/KeySequence">
      <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
          eType="#//commands/Command"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//commands/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KeySequence" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="keySequence" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//ApplicationElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ParameterizedCommand" instanceClassName="org.eclipse.core.commands.ParameterizedCommand"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="#//ApplicationElement">
      <eOperations name="getLocalizedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getLocalizedDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ui" nsURI="http://www.eclipse.org/ui/2010/UIModel/application/ui"
      nsPrefix="ui">
    <eClassifiers xsi:type="ecore:EClass" name="Context" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="#//IEclipseContext"
          transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variables" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//StringToStringMap" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dirtyable" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Input" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UIElement" abstract="true" eSuperTypes="#//ApplicationElement">
      <eOperations name="getLocalizedAccessibilityPhrase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="widget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
          transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="renderer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
          transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="toBeRendered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="onTop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eOpposite="#//ui/ElementContainer/children">
        <eGenericType eClassifier="#//ui/ElementContainer">
          <eTypeArguments eClassifier="#//ui/UIElement"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="curSharedRef" eType="#//ui/advanced/Placeholder"
          transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="visibleWhen" eType="#//ui/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessibilityPhrase"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ElementContainer" abstract="true"
        eSuperTypes="#//ui/UIElement">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//ui/UIElement"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          containment="true" eOpposite="#//ui/UIElement/parent">
        <eGenericType eTypeParameter="#//ui/ElementContainer/T"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="selectedElement">
        <eGenericType eTypeParameter="#//ui/ElementContainer/T"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UILabel" abstract="true" interface="true">
      <eOperations name="getLocalizedLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getLocalizedTooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericStack" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//ui/UIElement"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
        <eTypeArguments eTypeParameter="#//ui/GenericStack/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericTile" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//ui/UIElement"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
        <eTypeArguments eTypeParameter="#//ui/GenericTile/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericTrimContainer" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//ui/UIElement"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="side" lowerBound="1"
          eType="#//ui/SideValue"/>
      <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
        <eTypeArguments eTypeParameter="#//ui/GenericTrimContainer/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SideValue">
      <eLiterals name="Top"/>
      <eLiterals name="Bottom" value="1"/>
      <eLiterals name="Left" value="2"/>
      <eLiterals name="Right" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//ApplicationElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="CoreExpression" eSuperTypes="#//ui/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="coreExpressionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="coreExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
          transient="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SnippetContainer" abstract="true"
        interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="snippets" upperBound="-1"
          eType="#//ui/UIElement" containment="true"/>
    </eClassifiers>
    <eSubpackages name="menu" nsURI="http://www.eclipse.org/ui/2010/UIModel/application/ui/menu"
        nsPrefix="menu">
      <eClassifiers xsi:type="ecore:EEnum" name="ItemType">
        <eLiterals name="Push"/>
        <eLiterals name="Check" value="1"/>
        <eLiterals name="Radio" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true" eSuperTypes="#//ui/UIElement #//ui/UILabel">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
            eType="#//ui/menu/ItemType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HandledItem" abstract="true" eSuperTypes="#//ui/menu/Item">
        <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="#//commands/Command"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="wbCommand" eType="#//commands/ParameterizedCommand"
            transient="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
            eType="#//commands/Parameter" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MenuElement" abstract="true" eSuperTypes="#//ui/UIElement #//ui/UILabel">
        <eOperations name="getLocalizedMnemonics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mnemonics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MenuItem" abstract="true" eSuperTypes="#//ui/menu/Item #//ui/menu/MenuElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="MenuSeparator" eSuperTypes="#//ui/menu/MenuElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="Menu">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="true"/>
        <eGenericSuperTypes eClassifier="#//ui/menu/MenuElement"/>
        <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
          <eTypeArguments eClassifier="#//ui/menu/MenuElement"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MenuContribution">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionInParent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentId" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
          <eTypeArguments eClassifier="#//ui/menu/MenuElement"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PopupMenu" eSuperTypes="#//ui/menu/Menu #//ui/Context"/>
      <eClassifiers xsi:type="ecore:EClass" name="DirectMenuItem" eSuperTypes="#//ui/menu/MenuItem #//Contribution"/>
      <eClassifiers xsi:type="ecore:EClass" name="HandledMenuItem" eSuperTypes="#//ui/menu/MenuItem #//ui/menu/HandledItem"/>
      <eClassifiers xsi:type="ecore:EClass" name="ToolItem" abstract="true" eSuperTypes="#//ui/menu/Item #//ui/menu/ToolBarElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="menu" eType="#//ui/menu/Menu"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ToolBar">
        <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
          <eTypeArguments eClassifier="#//ui/menu/ToolBarElement"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ui/basic/TrimElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ToolBarElement" abstract="true"
          eSuperTypes="#//ui/UIElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="ToolControl" eSuperTypes="#//ui/menu/ToolBarElement #//Contribution #//ui/basic/TrimElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="HandledToolItem" eSuperTypes="#//ui/menu/ToolItem #//ui/menu/HandledItem"/>
      <eClassifiers xsi:type="ecore:EClass" name="DirectToolItem" eSuperTypes="#//ui/menu/ToolItem #//Contribution"/>
      <eClassifiers xsi:type="ecore:EClass" name="ToolBarSeparator" eSuperTypes="#//ui/menu/ToolBarElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="MenuContributions" abstract="true"
          interface="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="menuContributions"
            upperBound="-1" eType="#//ui/menu/MenuContribution" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RenderedMenu" eSuperTypes="#//ui/menu/Menu">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionManager"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
            transient="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RenderedToolBar" eSuperTypes="#//ui/menu/ToolBar">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionManager"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
            transient="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ToolBarContribution">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionInParent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
          <eTypeArguments eClassifier="#//ui/menu/ToolBarElement"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ToolBarContributions" abstract="true"
          interface="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="toolBarContributions"
            upperBound="-1" eType="#//ui/menu/ToolBarContribution" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TrimContribution">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionInParent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
          <eTypeArguments eClassifier="#//ui/basic/TrimElement"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TrimContributions" abstract="true"
          interface="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="trimContributions"
            upperBound="-1" eType="#//ui/menu/TrimContribution" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RenderedMenuItem" eSuperTypes="#//ui/menu/MenuItem">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
            transient="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OpaqueToolItem" eSuperTypes="#//ui/menu/ToolItem">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="opaqueItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
            transient="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OpaqueMenuItem" eSuperTypes="#//ui/menu/MenuItem">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="opaqueItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
            transient="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OpaqueMenuSeparator" eSuperTypes="#//ui/menu/MenuSeparator">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="opaqueItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
            transient="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OpaqueMenu" eSuperTypes="#//ui/menu/Menu"/>
      <eClassifiers xsi:type="ecore:EClass" name="DynamicMenuContribution" eSuperTypes="#//ui/menu/MenuItem #//Contribution"/>
    </eSubpackages>
    <eSubpackages name="basic" nsURI="http://www.eclipse.org/ui/2010/UIModel/application/ui/basic"
        nsPrefix="basic">
      <eClassifiers xsi:type="ecore:EClass" name="Part" eSuperTypes="#//ui/UIElement #//ui/basic/PartSashContainerElement #//ui/basic/StackElement #//Contribution #//ui/Context #//ui/UILabel #//commands/HandlerContainer #//ui/Dirtyable #//commands/Bindings #//ui/basic/WindowElement">
        <eOperations name="getLocalizedDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="menus" upperBound="-1"
            eType="#//ui/menu/Menu" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="toolbar" eType="#//ui/menu/ToolBar"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="closeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InputPart" eSuperTypes="#//ui/basic/Part #//ui/Input"/>
      <eClassifiers xsi:type="ecore:EClass" name="PartStack">
        <eGenericSuperTypes eClassifier="#//ui/GenericStack">
          <eTypeArguments eClassifier="#//ui/basic/StackElement"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ui/basic/PartSashContainerElement"/>
        <eGenericSuperTypes eClassifier="#//ui/basic/WindowElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PartSashContainer">
        <eGenericSuperTypes eClassifier="#//ui/GenericTile">
          <eTypeArguments eClassifier="#//ui/basic/PartSashContainerElement"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ui/basic/PartSashContainerElement"/>
        <eGenericSuperTypes eClassifier="#//ui/basic/WindowElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Window">
        <eStructuralFeatures xsi:type="ecore:EReference" name="mainMenu" eType="#//ui/menu/Menu"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
            defaultValueLiteral="-2147483648"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
            defaultValueLiteral="-2147483648"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
            defaultValueLiteral="-1"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
            defaultValueLiteral="-1"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="windows" upperBound="-1"
            eType="#//ui/basic/Window" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sharedElements" upperBound="-1"
            eType="#//ui/UIElement" containment="true"/>
        <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
          <eTypeArguments eClassifier="#//ui/basic/WindowElement"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ui/UILabel"/>
        <eGenericSuperTypes eClassifier="#//ui/Context"/>
        <eGenericSuperTypes eClassifier="#//commands/HandlerContainer"/>
        <eGenericSuperTypes eClassifier="#//commands/Bindings"/>
        <eGenericSuperTypes eClassifier="#//ui/SnippetContainer"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TrimmedWindow" eSuperTypes="#//ui/basic/Window">
        <eStructuralFeatures xsi:type="ecore:EReference" name="trimBars" upperBound="-1"
            eType="#//ui/basic/TrimBar" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TrimElement" abstract="true" eSuperTypes="#//ui/UIElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="PartSashContainerElement" abstract="true"
          interface="true" eSuperTypes="#//ui/UIElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="WindowElement" abstract="true" interface="true"
          eSuperTypes="#//ui/UIElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="TrimBar">
        <eGenericSuperTypes eClassifier="#//ui/GenericTrimContainer">
          <eTypeArguments eClassifier="#//ui/basic/TrimElement"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ui/UIElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StackElement" abstract="true" interface="true"
          eSuperTypes="#//ui/UIElement"/>
    </eSubpackages>
    <eSubpackages name="advanced" nsURI="http://www.eclipse.org/ui/2010/UIModel/application/ui/advanced"
        nsPrefix="advanced">
      <eClassifiers xsi:type="ecore:EClass" name="Placeholder" eSuperTypes="#//ui/UIElement #//ui/basic/PartSashContainerElement #//ui/basic/StackElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1"
            eType="#//ui/UIElement"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="closeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Perspective">
        <eStructuralFeatures xsi:type="ecore:EReference" name="windows" upperBound="-1"
            eType="#//ui/basic/Window" containment="true"/>
        <eGenericSuperTypes eClassifier="#//ui/ElementContainer">
          <eTypeArguments eClassifier="#//ui/basic/PartSashContainerElement"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ui/UILabel"/>
        <eGenericSuperTypes eClassifier="#//ui/Context"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PerspectiveStack">
        <eGenericSuperTypes eClassifier="#//ui/UIElement"/>
        <eGenericSuperTypes eClassifier="#//ui/GenericStack">
          <eTypeArguments eClassifier="#//ui/advanced/Perspective"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ui/basic/PartSashContainerElement"/>
        <eGenericSuperTypes eClassifier="#//ui/basic/WindowElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Area" eSuperTypes="#//ui/basic/PartSashContainer #//ui/UILabel"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="descriptor" nsURI="http://www.eclipse.org/ui/2010/UIModel/application/descriptor"
      nsPrefix="descriptor">
    <eSubpackages name="basic" nsURI="http://www.eclipse.org/ui/2010/UIModel/application/descriptor/basic"
        nsPrefix="basic">
      <eClassifiers xsi:type="ecore:EClass" name="PartDescriptor" eSuperTypes="#//ApplicationElement #//ui/UILabel #//commands/HandlerContainer #//commands/Bindings">
        <eOperations name="getLocalizedDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowMultiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="menus" upperBound="-1"
            eType="#//ui/menu/Menu" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="toolbar" eType="#//ui/menu/ToolBar"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="closeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirtyable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PartDescriptorContainer" abstract="true"
          interface="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="descriptors" upperBound="-1"
            eType="#//descriptor/basic/PartDescriptor" containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
