<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="application"
    nsURI="http://www.eclipse.org/ui/2008/UIModel" nsPrefix="application">
  <eClassifiers xsi:type="ecore:EClass" name="V____________ConstantsAndTypes_____________V"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ItemType">
    <eLiterals name="Push"/>
    <eLiterals name="Check" value="1"/>
    <eLiterals name="Radio" value="2"/>
    <eLiterals name="Separator" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SideValue">
    <eLiterals name="Top"/>
    <eLiterals name="Bottom" value="1"/>
    <eLiterals name="Left" value="2"/>
    <eLiterals name="Right" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IEclipseContext" instanceClassName="org.eclipse.e4.core.services.context.IEclipseContext"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ParameterizedCommand" instanceClassName="org.eclipse.core.commands.ParameterizedCommand"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringToStringMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="V____________Abstract_____________V"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" ordered="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contribution" abstract="true" eSuperTypes="#//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistedState" upperBound="-1"
        eType="#//StringToStringMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dirtyable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIElement" abstract="true" eSuperTypes="#//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="renderer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toBeRendered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onTop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eOpposite="#//ElementContainer/children">
      <eGenericType eClassifier="#//ElementContainer">
        <eTypeArguments eClassifier="#//UIElement"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UILabel" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="#//IEclipseContext"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variables" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//StringToStringMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="V_________AbstractContainers__________V"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementContainer" abstract="true" eSuperTypes="#//UIElement">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//UIElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        containment="true" eOpposite="#//UIElement/parent">
      <eGenericType eTypeParameter="#//ElementContainer/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedElement">
      <eGenericType eTypeParameter="#//ElementContainer/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericStack" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//UIElement"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eTypeParameter="#//GenericStack/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericTile" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//UIElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eTypeParameter="#//GenericTile/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="V______________MenusAndTBs_______________V"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//UIElement #//UILabel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ItemType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuItem" eSuperTypes="#//Menu #//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectMenuItem" eSuperTypes="#//Contribution #//MenuItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Menu">
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eClassifier="#//MenuItem"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToolItem">
    <eGenericSuperTypes eClassifier="#//Item"/>
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eClassifier="#//MenuItem"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectToolItem" eSuperTypes="#//ToolItem #//Contribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="ToolBar">
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eClassifier="#//ToolItem"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="V______________RCP_______________V"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Command" containment="true"/>
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eClassifier="#//Window"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Context"/>
    <eGenericSuperTypes eClassifier="#//HandlerContainer"/>
    <eGenericSuperTypes eClassifier="#//BindingContainer"/>
    <eGenericSuperTypes eClassifier="#//PartDescriptorContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSCElement" abstract="true" interface="true"
      eSuperTypes="#//UIElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Part" eSuperTypes="#//Contribution #//Context #//PSCElement #//UILabel #//HandlerContainer #//BindingContainer #//Dirtyable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="menus" upperBound="-1"
        eType="#//Menu" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolbar" eType="#//ToolBar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPart" eSuperTypes="#//Part #//Input"/>
  <eClassifiers xsi:type="ecore:EClass" name="PartDescriptor" eSuperTypes="#//Part">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowMultiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartDescriptorContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptors" upperBound="-1"
        eType="#//PartDescriptor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartStack">
    <eGenericSuperTypes eClassifier="#//GenericStack">
      <eTypeArguments eClassifier="#//Part"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//PSCElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartSashContainer">
    <eGenericSuperTypes eClassifier="#//GenericTile">
      <eTypeArguments eClassifier="#//PSCElement"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//PSCElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Window">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainMenu" eType="#//Menu"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eClassifier="#//PSCElement"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//UILabel"/>
    <eGenericSuperTypes eClassifier="#//Context"/>
    <eGenericSuperTypes eClassifier="#//HandlerContainer"/>
    <eGenericSuperTypes eClassifier="#//BindingContainer"/>
    <eGenericSuperTypes eClassifier="#//PSCElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelComponents">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ModelComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelComponent" eSuperTypes="#//PartDescriptorContainer #//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionInParent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//UIElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Command" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="handlers" upperBound="-1"
        eType="#//Handler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="V______________Commands_______________V"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BindingContainer" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//KeyBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" eSuperTypes="#//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//CommandParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandParameter" eSuperTypes="#//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Handler" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//Command"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HandlerContainer" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handlers" upperBound="-1"
        eType="#//Handler" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HandledItem" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wbCommand" eType="#//ParameterizedCommand"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HandledMenuItem" eSuperTypes="#//MenuItem #//HandledItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="HandledToolItem" eSuperTypes="#//ToolItem #//HandledItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyBinding" eSuperTypes="#//KeySequence #//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeySequence" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keySequence" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//ApplicationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="V______________Trim_______________V"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrimContainer" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//UIElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="side" lowerBound="1" eType="#//SideValue"/>
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eTypeParameter="#//TrimContainer/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WindowTrim">
    <eGenericSuperTypes eClassifier="#//TrimContainer">
      <eTypeArguments eClassifier="#//UIElement"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//PSCElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="V______________SharedElements_______________V"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Placeholder" eSuperTypes="#//UIElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//UIElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Perspective">
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eClassifier="#//PSCElement"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//UILabel"/>
    <eGenericSuperTypes eClassifier="#//Context"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerspectiveStack">
    <eGenericSuperTypes eClassifier="#//UIElement"/>
    <eGenericSuperTypes eClassifier="#//PSCElement"/>
    <eGenericSuperTypes eClassifier="#//GenericStack">
      <eTypeArguments eClassifier="#//Perspective"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="V_________Testing__________V" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestHarness">
    <eGenericSuperTypes eClassifier="#//ApplicationElement"/>
    <eGenericSuperTypes eClassifier="#//Command"/>
    <eGenericSuperTypes eClassifier="#//Context"/>
    <eGenericSuperTypes eClassifier="#//Contribution"/>
    <eGenericSuperTypes eClassifier="#//ElementContainer">
      <eTypeArguments eClassifier="#//UIElement"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Parameter"/>
    <eGenericSuperTypes eClassifier="#//Input"/>
    <eGenericSuperTypes eClassifier="#//Item"/>
    <eGenericSuperTypes eClassifier="#//UILabel"/>
    <eGenericSuperTypes eClassifier="#//Dirtyable"/>
  </eClassifiers>
</ecore:EPackage>
