/*******************************************************************************
 * Copyright (c) 2005 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the Common Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/cpl-v10.html
 * 
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

package org.eclipse.ui.internal.registry;

import java.util.Hashtable;
import java.util.Map;

import org.eclipse.core.runtime.IConfigurationElement;

/**
 * The KeywordRegistryReader is the registry reader for the keywords extension
 * point.
 * 
 */

public class KeywordRegistryReader extends RegistryReader {

	private static final String ATT_ID = "id"; //$NON-NLS-1$

	private static final String ATT_LABEL = "label"; //$NON-NLS-1$

	private static final String TAG_KEYWORD = "keyword"; //$NON-NLS-1$

	Hashtable keywords = new Hashtable();

	/**
	 * Create a new instance of the receiver.
	 * 
	 */
	public KeywordRegistryReader() {
		super();
	}

	/**
	 * Return the keywords generated by the receiver.
	 * 
	 * @return Map
	 */
	public Map getKeywords() {
		return keywords;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.eclipse.ui.internal.registry.RegistryReader#readElement(org.eclipse.core.runtime.IConfigurationElement)
	 */
	protected boolean readElement(IConfigurationElement element) {

		if (!element.getName().equals(TAG_KEYWORD))
			return false;

		String name = element.getAttribute(ATT_LABEL);
		String id = element.getAttribute(ATT_ID);
		keywords.put(id, name);
		return true;

	}

}
