/*******************************************************************************
 * Copyright (c) 2000, 2003 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the Common Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/cpl-v10.html
 * 
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.ui.internal.roles;

import java.util.EventObject;

/**
 * Event generated by changes in one or more Activities.  Contains a reference 
 * to the changed activities, both Activity objects that have become enabled and
 * those that have become disabled.
 */
public class ActivityManagerEvent extends EventObject {

    private Activity [] fEnabled, fDisabled;

	/**
	 * @param manager
	 */
	public ActivityManagerEvent(RoleManager manager, Activity [] enabled, Activity [] disabled) {
		super(manager);
        fEnabled = enabled;
        fDisabled = disabled;
	}
    
    /**
     * @return the source manager
     */
    public RoleManager getActivityManager() {
        return (RoleManager) getSource();
    }   
    
	/**
     * An array of recently disabled Activity objects.  Note that it's possible
     * for these objects to become enabled after this event is fired.
     *  
	 * @return recently disabled Activity objects
	 */
	protected Activity[] getDisabled() {
		return fDisabled;
	}

	/**
     * An array of recently enabled Activity objects.  Note that it's possible
     * for these objects to become disabled after this event is fired.
     * 
	 * @return recently enabled Activity objects
	 */
	protected Activity[] getEnabled() {
		return fEnabled;
	}
}
