package org.eclipse.ant.internal.ui;/* * (c) Copyright IBM Corp. 2000, 2001. * All Rights Reserved. */ import java.net.*;import org.eclipse.core.internal.runtime.Assert;import org.eclipse.jface.action.*;import org.eclipse.jface.resource.ImageDescriptor;import org.eclipse.jface.text.*;import org.eclipse.swt.SWT;import org.eclipse.swt.layout.*;import org.eclipse.swt.widgets.*;import org.eclipse.ui.part.ViewPart;import org.eclipse.ui.texteditor.FindReplaceAction;
public class AntConsole extends ViewPart {	public final static String CONSOLE_ID = "org.eclipse.ant.ui.antconsole";	public final static String PROPERTY_PREFIX_FIND = "find_action.";		private TextViewer viewer;	private Action copyAction;	private Action selectAllAction;	private Action clearOutputAction;	private Action findAction;	private IDocument document;
	/**
	 * Constructor for AntConsole
	 */
	public AntConsole() {
		super();
	}
	protected void addContributions() {		// Create the actions.		copyAction = new Action("&Copy") {			public void run() {				copySelectionToClipboard();			}		};		copyAction.setImageDescriptor(getImageDescriptor("icons/copy_edit.gif"));				selectAllAction = new Action("Select A&ll") {			public void run() {				selectAllText();			}		};				clearOutputAction = new Action("C&lear Output") {			public void run() {				clearOutput();			}		};		clearOutputAction.setImageDescriptor(getImageDescriptor("icons/clear.gif"));				findAction = new FindReplaceAction(			AntUIPlugin.getResourceBundle(),			PROPERTY_PREFIX_FIND,			this);		findAction.setEnabled(true);					MenuManager mgr = new MenuManager();		mgr.setRemoveAllWhenShown(true);		mgr.addMenuListener(new IMenuListener() {			public void menuAboutToShow(IMenuManager mgr) {				fillContextMenu(mgr);			}		});		Menu menu = mgr.createContextMenu(viewer.getControl());		viewer.getControl().setMenu(menu);	}	public void append(final String value) {		getViewSite().getShell().getDisplay().syncExec(new Runnable() {			public void run() {				//viewer.getTextWidget().append(value);				document.set(document.get() + value);				if (value.length() > 0)					viewer.revealRange(document.get().length() - 1, 1);			}		});	}		protected void copySelectionToClipboard() {		viewer.doOperation(viewer.COPY);	}		public void clearOutput() {		viewer.getTextWidget().setText("");	}		protected void fillContextMenu(IMenuManager manager) {		copyAction.setEnabled(viewer.canDoOperation(viewer.COPY));		selectAllAction.setEnabled(viewer.canDoOperation(viewer.SELECT_ALL));		manager.add(copyAction);		manager.add(selectAllAction);		manager.add(new Separator());		manager.add(findAction);		manager.add(clearOutputAction);	}	public Object getAdapter(Class required) {		if (IFindReplaceTarget.class.equals(required))			return viewer.getFindReplaceTarget();		return super.getAdapter(required);	}		protected ImageDescriptor getImageDescriptor(String relativePath) {		try {			URL installURL = AntUIPlugin.getPlugin().getDescriptor().getInstallURL();			URL url = new URL(installURL,relativePath);			return ImageDescriptor.createFromURL(url);		}		catch (MalformedURLException e) {			Assert.isTrue(false);			return null;		}	}	protected void selectAllText() {		viewer.doOperation(viewer.SELECT_ALL);	}	
	/**
	 * @see WorkbenchPart#setFocus()
	 */
	public void setFocus() {
	}

	/**
	 * @see WorkbenchPart#createPartControl(Composite)
	 */
	public void createPartControl(Composite parent) {		Composite composite = new Composite(parent, SWT.NULL);		composite.setLayout(new GridLayout());		composite.setLayoutData(new GridData(			GridData.VERTICAL_ALIGN_FILL | GridData.HORIZONTAL_ALIGN_FILL));		viewer = new TextViewer(composite,SWT.WRAP | SWT.BORDER | SWT.V_SCROLL | SWT.H_SCROLL);		GridData data = new GridData(GridData.FILL_BOTH);		viewer.setEditable(false);		viewer.getControl().setLayoutData(data);		document = new Document();		viewer.setDocument(document);		addContributions();		initializeToolbar();	}		protected void initializeToolbar() {		IToolBarManager tbm= getViewSite().getActionBars().getToolBarManager();		tbm.add(clearOutputAction);		getViewSite().getActionBars().updateActionBars();	}

}
